import React from 'react'

export const Info = {
    Shanghai_address:  [
        "Shanghai Thermo Fisher Calibration Lab",
        <br/>,
        "1234 Xingxu Court",
        <br/>,
        "Shanghai, China 9999"
    ],

    SantaClara_address:  [
        "Thermo Fisher Calibration Lab",
        <br/>,
        "3401 Leonard Court",
        <br/>,
        "Santa Clara, CA 95054"
    ],

    iso: 
    [`For service performed and calibration data, refer to the As Found Cabliration Report, and if needed
    the As Left Calibration Report, auto-generated by the referecne standard system.`,
    <br/>,
    <br/>,
    `Thermo Scientific follows current Good Manufacturing Practices and ISO 17025 procedures. Complete calibration and repair records are
    maintained at our service facility and are available for inspection.
    Unless otherwise specified, all stanadards are traceable to the National Institue of Standards and Technology (NIST).
    `,
    <br/>,
    <br/>,
    `The following calibration standards were used during this calibration:`
    ],
    docNo: `Doc#: F910-2908-001 Rev 4`
}